import m0 from './m0.png';
import m1 from './m1.png';
import m2 from './m2.png';
import m3 from './m3.png';
import w0 from './w0.png';
import w1 from './w1.png';
import w2 from './w2.png';
import w3 from './w3.png';
const avatars = { m0, m1, m2, m3, w0, w1, w2, w3 };
export default avatars;
